// OpenCode plugin installer — generates a project-level JS plugin and the current terminal launcher
package io.github.q110.aiterminaltools.monitor

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import io.github.q110.aiterminaltools.ProjectBasePath
import io.github.q110.aiterminaltools.settings.AiTerminalToolsSettings
import java.nio.file.Files
import java.nio.file.Path

/**
 * `.opencode/plugins` is project-level and must not contain tab-specific token/port values.
 * The generated JS plugin reads AITT_* from the current OpenCode process environment at runtime.
 */
class AiTurnOpenCodeInstaller(
    private val project: Project
) {
    private val log = Logger.getInstance(AiTurnOpenCodeInstaller::class.java)

    /** Install the OpenCode project plugin and return the current tab's launcher script paths */
    fun installOpenCodePlugin(basePath: Path, tabId: String, token: String, port: Int): AiTerminalLauncher.Paths {
        val validatedBasePath = ProjectBasePath.requireValid(basePath)
        val toolsDir = validatedBasePath.resolve(".idea").resolve("ai-terminal-tools")
        ProjectBasePath.requireValid(validatedBasePath)
        Files.createDirectories(toolsDir)

        writeJsPlugin(validatedBasePath)

        return writeLauncherScripts(toolsDir, tabId, token, port)
    }

    private fun writeJsPlugin(basePath: Path) {
        val pluginsDir = basePath.resolve(".opencode").resolve("plugins")
        ProjectBasePath.requireValid(basePath)
        Files.createDirectories(pluginsDir)
        val pluginFile = pluginsDir.resolve("ai-terminal-tools.js")

        // Keep JS content tab-independent so multiple OpenCode tabs do not interfere by rewriting one plugin.
        val js = """
            // Auto-generated by AI Terminal Tools
            // Sends OpenCode turn/file events to the IDEA plugin.
            // Runtime config is read from the current OpenCode process environment.
            const AITT_SOURCE = "opencode";

            ${AiTurnScriptCommon.load("common-post.js")}${AiTurnScriptCommon.load("common-path-helpers.js")}
            const WRITE_TOOLS = ["edit", "write", "apply_patch"];

            function isWriteTool(input) {
              return aittIsWriteToolName(input && input.tool, WRITE_TOOLS);
            }

            function writeToolPaths(input, output) {
              const args = (output && output.args) || (input && input.args) || {};
              if ((input && input.tool) === "apply_patch") return aittUnique(aittExtractPatchPaths(args.patchText));
              return aittUnique(aittExtractPaths(args));
            }

            function sessionID(ev) {
              return (ev && ev.properties && (ev.properties.sessionID || ev.properties.sessionId)) ||
                (ev && (ev.sessionID || ev.sessionId)) || "";
            }

            export var AiTerminalTools = async function() {
              return {
                event: async function(ctx) {
                  var ev = ctx.event;
                  if (!ev) return;

                  if (ev.type === "session.status") {
                    var status = ev.properties && ev.properties.status;
                    if (status && status.type === "busy") {
                      await aittPost("turn_start", { sessionID: sessionID(ev) });
                    }
                    return;
                  }

                  if (ev.type === "session.idle") {
                    await aittPost("turn_end", { sessionID: sessionID(ev) });
                    return;
                  }

                  if (ev.type === "file.edited") {
                    var file = ev.properties && ev.properties.file;
                    if (file) await aittPost("file_changed", { paths: [file], sessionID: sessionID(ev) });
                  }
                },

                "tool.execute.before": async function(input, output) {
                  if (!isWriteTool(input)) return;
                  var paths = writeToolPaths(input, output);
                  if (paths.length > 0) {
                    await aittPost("before_write", { paths: paths, sessionID: input && input.sessionID });
                  }
                },

                "tool.execute.after": async function(input, output) {
                  if (!isWriteTool(input)) return;
                  var paths = writeToolPaths(input, output);
                  if (paths.length > 0) {
                    await aittPost("file_changed", { paths: paths, sessionID: input && input.sessionID });
                  }
                }
              }
            }
        """.trimIndent()
        Files.writeString(pluginFile, js)
        log.info("Written OpenCode JS plugin to $pluginFile")
    }

    private fun writeLauncherScripts(
        toolsDir: Path, tabId: String, token: String, port: Int
    ): AiTerminalLauncher.Paths {
        val settings = AiTerminalToolsSettings.getInstance().getState()
        return AiTerminalLauncher.write(
            toolsDir = toolsDir,
            toolName = "opencode",
            tabId = tabId,
            token = token,
            port = port,
            customCommand = settings.openCodeTerminalCommand,
            defaultCommand = "opencode"
        )
    }

    fun cleanupLauncherScripts(basePath: Path, tabId: String) {
        AiTerminalLauncher.cleanup(
            basePath.resolve(".idea").resolve("ai-terminal-tools"), "opencode", tabId
        )
    }
}
