// OpenCode plugin installer — generates a project-level JS plugin and the current terminal launcher
package io.github.q110.aiterminaltools.monitor

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import io.github.q110.aiterminaltools.ProjectBasePath
import io.github.q110.aiterminaltools.settings.AiTerminalToolsSettings
import java.nio.file.Files
import java.nio.file.Path

/**
 * `.opencode/plugins` is project-level and must not contain tab-specific token/port values.
 * The generated JS plugin reads AITT_* from the current OpenCode process environment at runtime.
 */
class AiTurnOpenCodeInstaller(
    private val project: Project
) {
    private val log = Logger.getInstance(AiTurnOpenCodeInstaller::class.java)

    /** Install the OpenCode project plugin and return the current tab's launcher script paths */
    fun installOpenCodePlugin(basePath: Path, tabId: String, token: String, port: Int): AiTerminalLauncher.Paths {
        val validatedBasePath = ProjectBasePath.requireValid(basePath)
        val toolsDir = validatedBasePath.resolve(".idea").resolve("ai-terminal-tools")
        ProjectBasePath.requireValid(validatedBasePath)
        Files.createDirectories(toolsDir)

        writeJsPlugin(validatedBasePath)

        return writeLauncherScripts(toolsDir, tabId, token, port)
    }

    private fun writeJsPlugin(basePath: Path) {
        val pluginsDir = basePath.resolve(".opencode").resolve("plugins")
        ProjectBasePath.requireValid(basePath)
        Files.createDirectories(pluginsDir)
        val pluginFile = pluginsDir.resolve("ai-terminal-tools.js")

        // Keep JS content tab-independent so multiple OpenCode tabs do not interfere by rewriting one plugin.
        val js = buildString {
            appendLine("// Auto-generated by AI Terminal Tools")
            appendLine("// Sends OpenCode turn/file events to the IDEA plugin.")
            appendLine("// Runtime config is read from the current OpenCode process environment.")
            appendLine()
            appendLine("function env(name) {")
            appendLine("  if (typeof process !== \"undefined\" && process && process.env && process.env[name]) return process.env[name]")
            appendLine("  if (typeof Bun !== \"undefined\" && Bun && Bun.env) return Bun.env[name] || \"\"")
            appendLine("  return \"\"")
            appendLine("}")
            appendLine()
            appendLine("function config() {")
            appendLine("  return {")
            appendLine("    port: env(\"AITT_PORT\"),")
            appendLine("    token: env(\"AITT_TOKEN\"),")
            appendLine("    tabId: env(\"AITT_TAB_ID\")")
            appendLine("  }")
            appendLine("}")
            appendLine()
            appendLine("async function post(type, extra) {")
            appendLine("  var cfg = config()")
            appendLine("  if (!cfg.port || !cfg.token || !cfg.tabId) return")
            appendLine("  if (!extra) extra = {}")
            appendLine("  extra.source = \"opencode\"")
            appendLine("  extra.type = type")
            appendLine("  extra.tabId = cfg.tabId")
            appendLine("  try {")
            appendLine("    await fetch(\"http://127.0.0.1:\" + cfg.port + \"/event\", {")
            appendLine("      method: \"POST\",")
            appendLine("      headers: {")
            appendLine("        \"content-type\": \"application/json\",")
            appendLine("        \"x-aitt-token\": cfg.token")
            appendLine("      },")
            appendLine("      body: JSON.stringify(extra)")
            appendLine("    })")
            appendLine("  } catch (_) {}")
            appendLine("}")
            appendLine()
            appendLine("function sessionID(ev) {")
            appendLine("  return (ev && ev.properties && (ev.properties.sessionID || ev.properties.sessionId)) ||")
            appendLine("    (ev && (ev.sessionID || ev.sessionId)) || \"\"")
            appendLine("}")
            appendLine()
            appendLine("function extractPaths(obj, result) {")
            appendLine("  if (!result) result = []")
            appendLine("  if (!obj || typeof obj !== \"object\") return result")
            appendLine("  for (var key in obj) {")
            appendLine("    var val = obj[key]")
            appendLine("    if (typeof val === \"string\" && val.length > 0) {")
            appendLine("      var kl = key.toLowerCase()")
            appendLine("      if (kl === \"file\" || kl === \"path\" || kl === \"filepath\" ||")
            appendLine("          kl === \"file_path\" || kl === \"filename\" || kl === \"file_name\") {")
            appendLine("        if (val.length < 500 && val.indexOf(\"\\n\") < 0 &&")
            appendLine("            val.indexOf(\"{\") !== 0 && val.indexOf(\"[\") !== 0) {")
            appendLine("          result.push(val)")
            appendLine("        }")
            appendLine("      }")
            appendLine("    } else if (Array.isArray(val)) {")
            appendLine("      for (var i = 0; i < val.length; i++) extractPaths(val[i], result)")
            appendLine("    } else if (typeof val === \"object\" && val !== null) {")
            appendLine("      extractPaths(val, result)")
            appendLine("    }")
            appendLine("  }")
            appendLine("  return result")
            appendLine("}")
            appendLine()
            appendLine("function extractPatchPaths(patchText) {")
            appendLine("  var result = []")
            appendLine("  if (typeof patchText !== \"string\" || patchText.length === 0) return result")
            appendLine("  var lines = patchText.split(/\\r?\\n/)")
            appendLine("  for (var i = 0; i < lines.length; i++) {")
            appendLine("    var fileMatch = lines[i].match(/^\\*\\*\\* (?:Add|Update|Delete) File: (.+)$/)")
            appendLine("    var moveMatch = lines[i].match(/^\\*\\*\\* Move to: (.+)$/)")
            appendLine("    var path = fileMatch ? fileMatch[1] : (moveMatch ? moveMatch[1] : \"\")")
            appendLine("    if (path) result.push(path)")
            appendLine("  }")
            appendLine("  return result")
            appendLine("}")
            appendLine()
            appendLine("function isWriteTool(input) {")
            appendLine("  var tool = input && input.tool")
            appendLine("  return tool === \"edit\" || tool === \"write\" || tool === \"apply_patch\"")
            appendLine("}")
            appendLine()
            appendLine("function extractWriteToolPaths(input, output) {")
            appendLine("  var tool = input && input.tool")
            appendLine("  if (tool === \"apply_patch\") {")
            appendLine("    var patchArgs = (output && output.args) || (input && input.args) || {}")
            appendLine("    return unique(extractPatchPaths(patchArgs.patchText))")
            appendLine("  }")
            appendLine("  return unique(")
            appendLine("    extractPaths(output && output.args)")
            appendLine("      .concat(extractPaths(input && input.args))")
            appendLine("  )")
            appendLine("}")
            appendLine()
            appendLine("function unique(arr) {")
            appendLine("  var seen = {}")
            appendLine("  var out = []")
            appendLine("  for (var i = 0; i < arr.length; i++) {")
            appendLine("    if (!seen[arr[i]]) { seen[arr[i]] = true; out.push(arr[i]) }")
            appendLine("  }")
            appendLine("  return out")
            appendLine("}")
            appendLine()
            appendLine("export var AiTerminalTools = async function() {")
            appendLine("  return {")
            appendLine("    event: async function(ctx) {")
            appendLine("      var ev = ctx.event")
            appendLine("      if (!ev) return")
            appendLine()
            appendLine("      if (ev.type === \"session.status\") {")
            appendLine("        var status = ev.properties && ev.properties.status")
            appendLine("        if (status && status.type === \"busy\") {")
            appendLine("          await post(\"turn_start\", { sessionID: sessionID(ev) })")
            appendLine("        }")
            appendLine("        return")
            appendLine("      }")
            appendLine()
            appendLine("      if (ev.type === \"session.idle\") {")
            appendLine("        await post(\"turn_end\", { sessionID: sessionID(ev) })")
            appendLine("        return")
            appendLine("      }")
            appendLine()
            appendLine("      if (ev.type === \"file.edited\") {")
            appendLine("        var file = ev.properties && ev.properties.file")
            appendLine("        if (file) await post(\"file_changed\", { paths: [file], sessionID: sessionID(ev) })")
            appendLine("      }")
            appendLine("    },")
            appendLine()
            appendLine("    \"tool.execute.before\": async function(input, output) {")
            appendLine("      if (!isWriteTool(input)) return")
            appendLine("      var paths = extractWriteToolPaths(input, output)")
            appendLine("      if (paths.length > 0) {")
            appendLine("        await post(\"before_write\", { paths: paths, sessionID: input && input.sessionID })")
            appendLine("      }")
            appendLine("    },")
            appendLine()
            appendLine("    \"tool.execute.after\": async function(input, output) {")
            appendLine("      if (!isWriteTool(input)) return")
            appendLine("      var paths = extractWriteToolPaths(input, output)")
            appendLine("      if (paths.length > 0) {")
            appendLine("        await post(\"file_changed\", { paths: paths, sessionID: input && input.sessionID })")
            appendLine("      }")
            appendLine("    }")
            appendLine("  }")
            appendLine("}")
        }

        Files.writeString(pluginFile, js)
        log.info("Written OpenCode JS plugin to $pluginFile")
    }

    private fun writeLauncherScripts(
        toolsDir: Path, tabId: String, token: String, port: Int
    ): AiTerminalLauncher.Paths {
        val settings = AiTerminalToolsSettings.getInstance().getState()
        return AiTerminalLauncher.write(
            toolsDir = toolsDir,
            toolName = "opencode",
            tabId = tabId,
            token = token,
            port = port,
            customCommand = settings.openCodeTerminalCommand,
            defaultCommand = "opencode"
        )
    }

    fun cleanupLauncherScripts(basePath: Path, tabId: String) {
        AiTerminalLauncher.cleanup(
            basePath.resolve(".idea").resolve("ai-terminal-tools"), "opencode", tabId
        )
    }
}
