// Pi extension installer — generates a project-level TypeScript extension and the current terminal launcher
package io.github.q110.aiterminaltools.monitor

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import io.github.q110.aiterminaltools.ProjectBasePath
import io.github.q110.aiterminaltools.settings.AiTerminalToolsSettings
import java.nio.file.Files
import java.nio.file.Path

/**
 * `.pi/extensions` is project-level and must not contain tab-specific token/port values.
 * The generated TypeScript extension reads AITT_* from the current Pi process environment at runtime.
 */
class AiTurnPiInstaller(
    private val project: Project
) {
    private val log = Logger.getInstance(AiTurnPiInstaller::class.java)

    /** Install the Pi project extension and return the current tab's launcher script paths */
    fun installPiExtension(basePath: Path, tabId: String, token: String, port: Int): AiTerminalLauncher.Paths {
        val validatedBasePath = ProjectBasePath.requireValid(basePath)
        val toolsDir = validatedBasePath.resolve(".idea").resolve("ai-terminal-tools")
        ProjectBasePath.requireValid(validatedBasePath)
        Files.createDirectories(toolsDir)

        writeTsExtension(validatedBasePath)

        return writeLauncherScripts(toolsDir, tabId, token, port)
    }

    private fun writeTsExtension(basePath: Path) {
        val extensionsDir = basePath.resolve(".pi").resolve("extensions")
        ProjectBasePath.requireValid(basePath)
        Files.createDirectories(extensionsDir)
        val extensionFile = extensionsDir.resolve("ai-terminal-tools.ts")

        // Keep TS content tab-independent so multiple Pi tabs do not interfere by rewriting one extension.
        // Pi accepts plain JS inside .ts files.
        val ts = """
            // Auto-generated by AI Terminal Tools
            // Sends Pi turn/file events to the IDEA plugin.
            // Runtime config is read from the current Pi process environment.
            const AITT_SOURCE = "pi";

            ${AiTurnScriptCommon.load("common-post.js")}${AiTurnScriptCommon.load("common-path-helpers.js")}
            const WRITE_TOOLS = ["edit", "write"];

            export default function (pi) {
              // pi fires turn_start/turn_end after every loop step (each tool call).
              // agent_start/agent_settled fire once per prompt run and once the run
              // fully settles (finished or waiting for input), which matches a turn.
              pi.on("agent_start", async (event) => {
                await aittPost("turn_start", {});
              });

              pi.on("agent_settled", async (event) => {
                await aittPost("turn_end", {});
              });

              pi.on("tool_call", async (event) => {
                if (!aittIsWriteToolName(event.toolName, WRITE_TOOLS)) return;
                const paths = aittUnique(aittExtractPaths(event.input));
                if (paths.length > 0) {
                  await aittPost("before_write", { paths });
                }
              });

              pi.on("tool_result", async (event) => {
                if (!aittIsWriteToolName(event.toolName, WRITE_TOOLS)) return;
                const paths = aittUnique(aittExtractPaths(event.input));
                if (paths.length > 0) {
                  await aittPost("file_changed", { paths });
                }
              });
            }
        """.trimIndent()
        Files.writeString(extensionFile, ts)
        log.info("Written Pi TypeScript extension to $extensionFile")
    }

    private fun writeLauncherScripts(
        toolsDir: Path, tabId: String, token: String, port: Int
    ): AiTerminalLauncher.Paths {
        val settings = AiTerminalToolsSettings.getInstance().getState()
        return AiTerminalLauncher.write(
            toolsDir = toolsDir,
            toolName = "pi",
            tabId = tabId,
            token = token,
            port = port,
            customCommand = settings.piTerminalCommand,
            defaultCommand = "pi"
        )
    }

    fun cleanupLauncherScripts(basePath: Path, tabId: String) {
        AiTerminalLauncher.cleanup(
            basePath.resolve(".idea").resolve("ai-terminal-tools"), "pi", tabId
        )
    }
}
