// Pi extension installer — generates a project-level TypeScript extension and the current terminal launcher
package io.github.q110.aiterminaltools.monitor

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import io.github.q110.aiterminaltools.ProjectBasePath
import io.github.q110.aiterminaltools.settings.AiTerminalToolsSettings
import java.nio.file.Files
import java.nio.file.Path

/**
 * `.pi/extensions` is project-level and must not contain tab-specific token/port values.
 * The generated TypeScript extension reads AITT_* from the current Pi process environment at runtime.
 */
class AiTurnPiInstaller(
    private val project: Project
) {
    private val log = Logger.getInstance(AiTurnPiInstaller::class.java)

    /** Install the Pi project extension and return the current tab's launcher script paths */
    fun installPiExtension(basePath: Path, tabId: String, token: String, port: Int): AiTerminalLauncher.Paths {
        val validatedBasePath = ProjectBasePath.requireValid(basePath)
        val toolsDir = validatedBasePath.resolve(".idea").resolve("ai-terminal-tools")
        ProjectBasePath.requireValid(validatedBasePath)
        Files.createDirectories(toolsDir)

        writeTsExtension(validatedBasePath)

        return writeLauncherScripts(toolsDir, tabId, token, port)
    }

    private fun writeTsExtension(basePath: Path) {
        val extensionsDir = basePath.resolve(".pi").resolve("extensions")
        ProjectBasePath.requireValid(basePath)
        Files.createDirectories(extensionsDir)
        val extensionFile = extensionsDir.resolve("ai-terminal-tools.ts")

        // Keep TypeScript content tab-independent so multiple Pi tabs do not interfere by rewriting one extension.
        val ts = buildString {
            appendLine("// Auto-generated by AI Terminal Tools")
            appendLine("// Sends Pi turn/file events to the IDEA plugin.")
            appendLine("// Runtime config is read from the current Pi process environment.")
            appendLine()
            appendLine("const PORT = (typeof process !== \"undefined\" && process.env && process.env.AITT_PORT) || \"\";")
            appendLine("const TOKEN = (typeof process !== \"undefined\" && process.env && process.env.AITT_TOKEN) || \"\";")
            appendLine("const TAB_ID = (typeof process !== \"undefined\" && process.env && process.env.AITT_TAB_ID) || \"\";")
            appendLine()
            appendLine("async function post(type: string, extra: any = {}) {")
            appendLine("  if (!PORT || !TOKEN || !TAB_ID) return;")
            appendLine("  extra.source = \"pi\";")
            appendLine("  extra.type = type;")
            appendLine("  extra.tabId = TAB_ID;")
            appendLine("  try {")
            appendLine("    await fetch(`http://127.0.0.1:\${PORT}/event`, {")
            appendLine("      method: \"POST\",")
            appendLine("      headers: {")
            appendLine("        \"content-type\": \"application/json\",")
            appendLine("        \"x-aitt-token\": TOKEN")
            appendLine("      },")
            appendLine("      body: JSON.stringify(extra)")
            appendLine("    });")
            appendLine("  } catch {}");
            appendLine("}")
            appendLine()
            appendLine("function extractPaths(obj: any, result: string[] = []): string[] {")
            appendLine("  if (!obj || typeof obj !== \"object\") return result;")
            appendLine("  for (const key in obj) {")
            appendLine("    const val = obj[key];")
            appendLine("    if (typeof val === \"string\" && val.length > 0) {")
            appendLine("      const kl = key.toLowerCase();")
            appendLine("      if (kl === \"file\" || kl === \"path\" || kl === \"filepath\" ||")
            appendLine("          kl === \"file_path\" || kl === \"filename\" || kl === \"file_name\") {")
            appendLine("        if (val.length < 500 && val.indexOf(\"\\n\") < 0 &&")
            appendLine("            val.indexOf(\"{\") !== 0 && val.indexOf(\"[\") !== 0) {")
            appendLine("          result.push(val);")
            appendLine("        }")
            appendLine("      }")
            appendLine("    } else if (Array.isArray(val)) {")
            appendLine("      for (let i = 0; i < val.length; i++) extractPaths(val[i], result);")
            appendLine("    } else if (typeof val === \"object\" && val !== null) {")
            appendLine("      extractPaths(val, result);")
            appendLine("    }")
            appendLine("  }")
            appendLine("  return result;")
            appendLine("}")
            appendLine()
            appendLine("function isWriteTool(toolName: string): boolean {")
            appendLine("  return toolName === \"edit\" || toolName === \"write\";")
            appendLine("}")
            appendLine()
            appendLine("function unique(arr: string[]): string[] {")
            appendLine("  const seen: any = {};")
            appendLine("  const out: string[] = [];")
            appendLine("  for (let i = 0; i < arr.length; i++) {")
            appendLine("    if (!seen[arr[i]]) { seen[arr[i]] = true; out.push(arr[i]); }")
            appendLine("  }")
            appendLine("  return out;")
            appendLine("}")
            appendLine()
            appendLine("export default function (pi: any) {")
            appendLine("  pi.on(\"turn_start\", async (event: any) => {")
            appendLine("    await post(\"turn_start\", {});")
            appendLine("  });")
            appendLine()
            appendLine("  pi.on(\"turn_end\", async (event: any) => {")
            appendLine("    await post(\"turn_end\", {});")
            appendLine("  });")
            appendLine()
            appendLine("  pi.on(\"tool_call\", async (event: any) => {")
            appendLine("    if (!isWriteTool(event.toolName)) return;")
            appendLine("    const paths = unique(extractPaths(event.input));")
            appendLine("    if (paths.length > 0) {")
            appendLine("      await post(\"before_write\", { paths });")
            appendLine("    }")
            appendLine("  });")
            appendLine()
            appendLine("  pi.on(\"tool_result\", async (event: any) => {")
            appendLine("    if (!isWriteTool(event.toolName)) return;")
            appendLine("    const paths = unique(extractPaths(event.input));")
            appendLine("    if (paths.length > 0) {")
            appendLine("      await post(\"file_changed\", { paths });")
            appendLine("    }")
            appendLine("  });")
            appendLine("}")
        }

        Files.writeString(extensionFile, ts)
        log.info("Written Pi TypeScript extension to $extensionFile")
    }

    private fun writeLauncherScripts(
        toolsDir: Path, tabId: String, token: String, port: Int
    ): AiTerminalLauncher.Paths {
        val settings = AiTerminalToolsSettings.getInstance().getState()
        return AiTerminalLauncher.write(
            toolsDir = toolsDir,
            toolName = "pi",
            tabId = tabId,
            token = token,
            port = port,
            customCommand = settings.piTerminalCommand,
            defaultCommand = "pi"
        )
    }

    fun cleanupLauncherScripts(basePath: Path, tabId: String) {
        AiTerminalLauncher.cleanup(
            basePath.resolve(".idea").resolve("ai-terminal-tools"), "pi", tabId
        )
    }
}
