// Codex CLI installer — configures per-launch completion notifications and launchers.
package io.github.q110.aiterminaltools.monitor

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import io.github.q110.aiterminaltools.ProjectBasePath
import io.github.q110.aiterminaltools.settings.AiTerminalToolsSettings
import java.nio.file.Files
import java.nio.file.Path

class AiTurnCodexInstaller(private val project: Project) {
    private val log = Logger.getInstance(AiTurnCodexInstaller::class.java)

    fun installCodexNotifier(basePath: Path, tabId: String, token: String, port: Int): AiTerminalLauncher.Paths {
        val validatedBasePath = ProjectBasePath.requireValid(basePath)
        val toolsDir = validatedBasePath.resolve(".idea").resolve("ai-terminal-tools")
        Files.createDirectories(toolsDir)
        val notifier = writeNotifierScripts(toolsDir)
        val settings = AiTerminalToolsSettings.getInstance().getState()
        val baseCommand = settings.codexTerminalCommand.trim().ifEmpty { "codex" }
        return AiTerminalLauncher.write(
            toolsDir, "codex", tabId, token, port,
            customCommand = "$baseCommand ${notificationConfig(notifier)}",
            defaultCommand = "codex ${notificationConfig(notifier)}"
        )
    }

    private fun writeNotifierScripts(toolsDir: Path): Path {
        val sh = toolsDir.resolve("codex-notify.sh")
        Files.writeString(sh, """#!/usr/bin/env bash
# Auto-generated by AI Terminal Tools. Codex passes completion JSON on stdin.
cat >/dev/null
curl -fsS --max-time 2 -X POST "http://127.0.0.1:${'$'}{AITT_PORT}/event" -H "Content-Type: application/json" -H "X-AITT-Token: ${'$'}{AITT_TOKEN}" --data "{\"source\":\"codex\",\"type\":\"turn_end\",\"tabId\":\"${'$'}{AITT_TAB_ID}\"}" >/dev/null 2>&1 || true
""")
        try { sh.toFile().setExecutable(true, false) } catch (_: Throwable) {}
        val cmd = toolsDir.resolve("codex-notify.cmd")
        Files.writeString(cmd, "@echo off\r\ntype nul >nul\r\npowershell -NoProfile -ExecutionPolicy Bypass -Command \"[Console]::In.ReadToEnd() | Out-Null; Invoke-WebRequest -UseBasicParsing -Method Post -Uri 'http://127.0.0.1:%AITT_PORT%/event' -Headers @{'X-AITT-Token'='%AITT_TOKEN%'} -ContentType 'application/json' -Body '{\\\"source\\\":\\\"codex\\\",\\\"type\\\":\\\"turn_end\\\",\\\"tabId\\\":\\\"%AITT_TAB_ID%\\\"}' | Out-Null\"\r\n")
        log.info("Written Codex completion notifier to $sh")
        return sh
    }

    private fun notificationConfig(sh: Path): String {
        val command = if (System.getProperty("os.name", "").lowercase().contains("win")) {
            "[\"cmd\", \"/c\", \"${sh.parent.resolve("codex-notify.cmd").toString().replace('\\', '/')}\"]"
        } else {
            "[\"${sh.toAbsolutePath()}\"]"
        }
        return "-c 'notify=$command'"
    }

    fun cleanupLauncherScripts(basePath: Path, tabId: String) {
        AiTerminalLauncher.cleanup(basePath.resolve(".idea").resolve("ai-terminal-tools"), "codex", tabId)
    }
}
